#!/bin/sh

### BEGIN INIT INFO
# Provides:          set_comitup_hostname_once
# Required-Start:    comitup
# Required-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Rename hostname per Comitup Hotspot AP name
# Description:
#  This service sets the system hostname to the name that the Comitup
#  service uses for it's hotspot AP name, then deletes itself.
### END INIT INFO

. /lib/lsb/init-functions

case "$1" in
  start)
    log_daemon_msg "Starting set_comitup_hostname_once"

    APNAME=$(comitup -i | grep apname: | awk '{print $2}')
    
    if [ ! -z $APNAME ] ; then
      echo "Set hostname to $APNAME"
      echo $APNAME > /etc/hostname
      echo "127.0.0.1\t$APNAME" >/etc/hosts
      hostname $APNAME

      update-rc.d set_comitup_hostname_once remove &&
      rm /etc/init.d/set_comitup_hostname_once &&
      log_end_msg $?
    fi

    ;;
  *)
    echo "Usage: $0 start" >&2
    exit 3
    ;;
esac
